### ISSUE TITLE
Grunt

### ISSUE THREAD

**Issue by Farof** [Farof/heroprotocoljs#16]
Grunt could help improve the code quality and prevent mistakes.
#8 does not work on both my Windows and OS X, `grunt lint` works for a while and then gives me a memory error.

Would be nice to make it work. Low priority for me.

**Comment by jnovack** [comment]
It's crashing because you have a shit-ton of other files and directories and 'watch' is trying to watch all of them.

I've updated the lint to only watch `./*.js, 'bin/*.js', 'examples/*.js', 'lib/*.js', 'test/*.js'`.

If you make a new folder called "all_the_javascript_on_my_harddrive", it will no longer try to lint it.
