### ISSUE TITLE
extract.js - add option to skip existing files

### ISSUE THREAD

**Issue by Farof** [Farof/heroprotocoljs#18]
Right now the tool overrides existing files. Add option to skip them. Would help and save time if a very long extraction is cancelled or crashes and you restart it.

**Comment by jnovack** [comment]
To do this right, there's one caveat with this.  We either have to load the existing file (and validate it) or have to extract the files in order to see if they are properly created (by comparing sizes / checksum).  When it's a 30MB file, it chews up seconds without providing benefit.

If I extract+write every file, I do it in an average of 3.631 seconds.  If I extract+compare, I do it in 3.211 seconds, BARELY any savings, it's near pointless.

I could skip the file if it is over 0 bytes, however, we could have a corrupted file that was written last time, and the `--skip-existing` option would not overwrite it.

How would you like to do this?

**Comment by Farof** [comment]
Done 859ed5836b4c9b230ee3e6edb2330f4dbce1a82d.

Nothing fancy, just a check if the file exists.
